CREATE TABLE IF NOT EXISTS public.skill (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  rotulo TEXT NOT NULL,
  categoria TEXT NOT NULL CHECK (categoria IN ('manual', 'mental', 'social', 'tecnica', 'ecologica', 'artistica'))
);

ALTER TABLE public.skill ENABLE ROW LEVEL SECURITY;
CREATE POLICY "skill_select_authenticated" ON public.skill FOR SELECT TO authenticated USING (true);

-- Seed do catálogo ~52 skills
INSERT INTO public.skill (slug, rotulo, categoria) VALUES
  ('agro-sintropico', 'Agrofloresta sintrópica', 'ecologica'),
  ('apicultura', 'Apicultura', 'ecologica'),
  ('audiovisual', 'Audiovisual', 'tecnica'),
  ('bioconstrucao', 'Bioconstrução', 'manual'),
  ('canto', 'Canto e voz', 'artistica'),
  ('cartografia', 'Cartografia comunitária', 'tecnica'),
  ('ceramica', 'Cerâmica', 'artistica'),
  ('comunicacao-naoviolenta', 'Comunicação não violenta', 'social'),
  ('costura', 'Costura', 'manual'),
  ('culinaria-vegana', 'Culinária vegana', 'manual'),
  ('danca', 'Dança', 'artistica'),
  ('design', 'Design gráfico', 'tecnica'),
  ('educacao-infantil', 'Educação infantil', 'social'),
  ('educacao-popular', 'Educação popular', 'social'),
  ('escrita', 'Escrita criativa', 'artistica'),
  ('facilitacao', 'Facilitação de grupos', 'social'),
  ('fermentacao', 'Fermentação', 'manual'),
  ('fitoterapia', 'Fitoterapia', 'ecologica'),
  ('fotografia', 'Fotografia', 'artistica'),
  ('gestao', 'Gestão de projetos', 'mental'),
  ('horticultura', 'Horticultura', 'ecologica'),
  ('idiomas-ingles', 'Inglês', 'mental'),
  ('idiomas-espanhol', 'Espanhol', 'mental'),
  ('jardinagem', 'Jardinagem', 'ecologica'),
  ('marcenaria', 'Marcenaria', 'manual'),
  ('massagem', 'Massagem', 'manual'),
  ('mediacao-conflitos', 'Mediação de conflitos', 'social'),
  ('mecanica-basica', 'Mecânica básica', 'tecnica'),
  ('meditacao', 'Meditação', 'social'),
  ('musica', 'Música instrumental', 'artistica'),
  ('panificacao', 'Panificação artesanal', 'manual'),
  ('pedreiro', 'Pedreiro', 'manual'),
  ('pesca-sustentavel', 'Pesca sustentável', 'ecologica'),
  ('pintura', 'Pintura', 'artistica'),
  ('plantio', 'Plantio de mudas', 'ecologica'),
  ('podcast', 'Podcast', 'tecnica'),
  ('programacao', 'Programação web', 'tecnica'),
  ('reciclagem', 'Reciclagem', 'ecologica'),
  ('reiki', 'Reiki', 'social'),
  ('saneamento', 'Saneamento ecológico', 'ecologica'),
  ('sapataria', 'Sapataria', 'manual'),
  ('serralheria', 'Serralheria', 'manual'),
  ('teatro', 'Teatro', 'artistica'),
  ('terapia-floral', 'Terapia floral', 'social'),
  ('terapia-pratica', 'Atendimento terapêutico', 'social'),
  ('tradicao-oral', 'Tradição oral', 'social'),
  ('traducao', 'Tradução', 'mental'),
  ('turismo-comunitario', 'Turismo comunitário', 'social'),
  ('uxdesign', 'UX design', 'tecnica'),
  ('video-edicao', 'Edição de vídeo', 'tecnica'),
  ('voluntariado-coord', 'Coordenação de voluntariado', 'social'),
  ('yoga', 'Yoga', 'social'),
  ('zumba', 'Zumba', 'artistica')
ON CONFLICT (slug) DO NOTHING;
